services:
  api:
    image: registry.cn-hangzhou.aliyuncs.com/hanfangyuan/fastapi-nextjs-api:main
    pull_policy: always
    env_file:
      - ./.env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=1
      - MIGRATION_ENABLED=true
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
  web:
    image: registry.cn-hangzhou.aliyuncs.com/hanfangyuan/fastapi-nextjs-web:main
    pull_policy: always
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - api
    restart: unless-stopped

  postgres:
    image: registry.cn-hangzhou.aliyuncs.com/hanfangyuan/postgres:17-alpine
    ports:
      - "35432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-fastapi_nextjs}
      TZ: Asia/Shanghai
    command:
      - postgres
      - -c
      - max_connections=100
      - -c
      - idle_in_transaction_session_timeout=3600000
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data

  redis:
    image: registry.cn-hangzhou.aliyuncs.com/hanfangyuan/redis:8.0-alpine
    ports:
      - "36379:6379"
    environment:
      TZ: Asia/Shanghai
    command:
      - redis-server
      - --requirepass
      - ${REDIS_PASSWORD:-fastapi_nextjs}
      - --save
      - "60"
      - "1"
      - --loglevel
      - warning
      - --protected-mode
      - yes
    volumes:
      - ./volumes/redis/data:/data
    restart: unless-stopped

  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/hanfangyuan/nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
      - web
    restart: unless-stopped
